steps:
  #update the composer environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['composer', 'environments', 'update', '${_COMPOSER_NAME}', '--update-pypi-packages-from-file', 'requirements-composer.txt', '--location', '${_COMPOSER_ZONE}']
    id: 'update-composer-env'
timeout: 3600s #1 hour timeout accommodates the long running Composer upgrade operation
