name: Update Composer Environment

on: 
  push:
    branches:
      - main

jobs:
  update-composer-env:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info #update this to composer thing later
